/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xla_service.proto

package xla;

public final class XlaServiceOuterClass {
  private XlaServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021xla_service.proto\022\003xla\032!tensorflow/com" +
      "piler/xla/xla.proto2\352\n\n\nXlaService\022?\n\nUn" +
      "register\022\026.xla.UnregisterRequest\032\027.xla.U" +
      "nregisterResponse\"\000\022Q\n\020DeconstructTuple\022" +
      "\034.xla.DeconstructTupleRequest\032\035.xla.Deco" +
      "nstructTupleResponse\"\000\0223\n\006Unpack\022\022.xla.U" +
      "npackRequest\032\023.xla.UnpackResponse\"\000\0229\n\010G" +
      "etShape\022\024.xla.GetShapeRequest\032\025.xla.GetS" +
      "hapeResponse\"\000\022^\n\030GetComputationGraphSta" +
      "ts\022!.xla.ComputationGraphStatsRequest\032\035." +
      "xla.ComputationStatsResponse\"\000\0229\n\010LoadDa" +
      "ta\022\024.xla.LoadDataRequest\032\025.xla.LoadDataR" +
      "esponse\"\000\022Q\n\020TransferToClient\022\034.xla.Tran" +
      "sferToClientRequest\032\035.xla.TransferToClie" +
      "ntResponse\"\000\022Q\n\020TransferToServer\022\034.xla.T" +
      "ransferToServerRequest\032\035.xla.TransferToS" +
      "erverResponse\"\000\022Q\n\020TransferToInfeed\022\034.xl" +
      "a.TransferToInfeedRequest\032\035.xla.Transfer" +
      "ToInfeedResponse\"\000\022Z\n\023TransferFromOutfee" +
      "d\022\037.xla.TransferFromOutfeedRequest\032 .xla" +
      ".TransferFromOutfeedResponse\"\000\022B\n\013ResetD" +
      "evice\022\027.xla.ResetDeviceRequest\032\030.xla.Res" +
      "etDeviceResponse\"\000\022X\n\024ComputeConstantGra" +
      "ph\022 .xla.ComputeConstantGraphRequest\032\034.x" +
      "la.ComputeConstantResponse\"\000\022Q\n\020GetDevic" +
      "eHandles\022\034.xla.GetDeviceHandlesRequest\032\035" +
      ".xla.GetDeviceHandlesResponse\"\000\022Z\n\023Creat" +
      "eChannelHandle\022\037.xla.CreateChannelHandle" +
      "Request\032 .xla.CreateChannelHandleRespons" +
      "e\"\000\0226\n\007Compile\022\023.xla.CompileRequest\032\024.xl" +
      "a.CompileResponse\"\000\0226\n\007Execute\022\023.xla.Exe" +
      "cuteRequest\032\024.xla.ExecuteResponse\"\000\022X\n\024E" +
      "xecuteGraphParallel\022 .xla.ExecuteGraphPa" +
      "rallelRequest\032\034.xla.ExecuteParallelRespo" +
      "nse\"\000\022Q\n\020WaitForExecution\022\034.xla.WaitForE" +
      "xecutionRequest\032\035.xla.WaitForExecutionRe" +
      "sponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xla.Xla.getDescriptor(),
        }, assigner);
    xla.Xla.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
