/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_log.proto

package org.tensorflow.util.testlog;

public interface GPUInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GPUInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "Tesla K40c"
   * </pre>
   *
   * <code>string model = 1;</code>
   */
  java.lang.String getModel();
  /**
   * <pre>
   * e.g. "Tesla K40c"
   * </pre>
   *
   * <code>string model = 1;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * Final entry in output of "nvidia-smi -L"
   * </pre>
   *
   * <code>string uuid = 2;</code>
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * Final entry in output of "nvidia-smi -L"
   * </pre>
   *
   * <code>string uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * e.g. "0000:04:00.0"
   * </pre>
   *
   * <code>string bus_id = 3;</code>
   */
  java.lang.String getBusId();
  /**
   * <pre>
   * e.g. "0000:04:00.0"
   * </pre>
   *
   * <code>string bus_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getBusIdBytes();
}
