/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_graph.proto

package org.tensorflow.framework;

public interface CollectionDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CollectionDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.CollectionDef.NodeList node_list = 1;</code>
   */
  boolean hasNodeList();
  /**
   * <code>.tensorflow.CollectionDef.NodeList node_list = 1;</code>
   */
  org.tensorflow.framework.CollectionDef.NodeList getNodeList();
  /**
   * <code>.tensorflow.CollectionDef.NodeList node_list = 1;</code>
   */
  org.tensorflow.framework.CollectionDef.NodeListOrBuilder getNodeListOrBuilder();

  /**
   * <code>.tensorflow.CollectionDef.BytesList bytes_list = 2;</code>
   */
  boolean hasBytesList();
  /**
   * <code>.tensorflow.CollectionDef.BytesList bytes_list = 2;</code>
   */
  org.tensorflow.framework.CollectionDef.BytesList getBytesList();
  /**
   * <code>.tensorflow.CollectionDef.BytesList bytes_list = 2;</code>
   */
  org.tensorflow.framework.CollectionDef.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>.tensorflow.CollectionDef.Int64List int64_list = 3;</code>
   */
  boolean hasInt64List();
  /**
   * <code>.tensorflow.CollectionDef.Int64List int64_list = 3;</code>
   */
  org.tensorflow.framework.CollectionDef.Int64List getInt64List();
  /**
   * <code>.tensorflow.CollectionDef.Int64List int64_list = 3;</code>
   */
  org.tensorflow.framework.CollectionDef.Int64ListOrBuilder getInt64ListOrBuilder();

  /**
   * <code>.tensorflow.CollectionDef.FloatList float_list = 4;</code>
   */
  boolean hasFloatList();
  /**
   * <code>.tensorflow.CollectionDef.FloatList float_list = 4;</code>
   */
  org.tensorflow.framework.CollectionDef.FloatList getFloatList();
  /**
   * <code>.tensorflow.CollectionDef.FloatList float_list = 4;</code>
   */
  org.tensorflow.framework.CollectionDef.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>.tensorflow.CollectionDef.AnyList any_list = 5;</code>
   */
  boolean hasAnyList();
  /**
   * <code>.tensorflow.CollectionDef.AnyList any_list = 5;</code>
   */
  org.tensorflow.framework.CollectionDef.AnyList getAnyList();
  /**
   * <code>.tensorflow.CollectionDef.AnyList any_list = 5;</code>
   */
  org.tensorflow.framework.CollectionDef.AnyListOrBuilder getAnyListOrBuilder();

  org.tensorflow.framework.CollectionDef.KindCase getKindCase();
}
