/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boosted_trees.proto

package org.tensorflow.framework;

public interface DebugOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.boosted_trees.DebugOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Return the logits and associated feature splits across prediction paths for
   * each tree, for every example, at predict time. We will use these values to
   * compute DFCs in Python, by subtracting each child prediction from its
   * parent prediction and associating this change with its respective feature
   * id.
   * </pre>
   *
   * <code>repeated int32 feature_ids = 1;</code>
   */
  java.util.List<java.lang.Integer> getFeatureIdsList();
  /**
   * <pre>
   * Return the logits and associated feature splits across prediction paths for
   * each tree, for every example, at predict time. We will use these values to
   * compute DFCs in Python, by subtracting each child prediction from its
   * parent prediction and associating this change with its respective feature
   * id.
   * </pre>
   *
   * <code>repeated int32 feature_ids = 1;</code>
   */
  int getFeatureIdsCount();
  /**
   * <pre>
   * Return the logits and associated feature splits across prediction paths for
   * each tree, for every example, at predict time. We will use these values to
   * compute DFCs in Python, by subtracting each child prediction from its
   * parent prediction and associating this change with its respective feature
   * id.
   * </pre>
   *
   * <code>repeated int32 feature_ids = 1;</code>
   */
  int getFeatureIds(int index);

  /**
   * <code>repeated float logits_path = 2;</code>
   */
  java.util.List<java.lang.Float> getLogitsPathList();
  /**
   * <code>repeated float logits_path = 2;</code>
   */
  int getLogitsPathCount();
  /**
   * <code>repeated float logits_path = 2;</code>
   */
  float getLogitsPath(int index);
}
