/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_attributes.proto

package org.tensorflow.framework;

public interface DeviceLocalityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.DeviceLocality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional bus locality of device.  Default value of 0 means
   * no specific locality.  Specific localities are indexed from 1.
   * </pre>
   *
   * <code>int32 bus_id = 1;</code>
   */
  int getBusId();

  /**
   * <pre>
   * Optional NUMA locality of device.
   * </pre>
   *
   * <code>int32 numa_node = 2;</code>
   */
  int getNumaNode();

  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  boolean hasLinks();
  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  org.tensorflow.framework.LocalLinks getLinks();
  /**
   * <pre>
   * Optional local interconnect links to other devices.
   * </pre>
   *
   * <code>.tensorflow.LocalLinks links = 3;</code>
   */
  org.tensorflow.framework.LocalLinksOrBuilder getLinksOrBuilder();
}
