/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: function.proto

package org.tensorflow.framework;

public interface GradientDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GradientDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The function name.
   * </pre>
   *
   * <code>string function_name = 1;</code>
   */
  java.lang.String getFunctionName();
  /**
   * <pre>
   * The function name.
   * </pre>
   *
   * <code>string function_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();

  /**
   * <pre>
   * The gradient function's name.
   * </pre>
   *
   * <code>string gradient_func = 2;</code>
   */
  java.lang.String getGradientFunc();
  /**
   * <pre>
   * The gradient function's name.
   * </pre>
   *
   * <code>string gradient_func = 2;</code>
   */
  com.google.protobuf.ByteString
      getGradientFuncBytes();
}
