/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph_transfer_info.proto

package org.tensorflow.framework;

public interface GraphTransferNodeOutputInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GraphTransferNodeOutputInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 node_id = 1;</code>
   */
  int getNodeId();

  /**
   * <code>repeated int32 max_byte_size = 2;</code>
   */
  java.util.List<java.lang.Integer> getMaxByteSizeList();
  /**
   * <code>repeated int32 max_byte_size = 2;</code>
   */
  int getMaxByteSizeCount();
  /**
   * <code>repeated int32 max_byte_size = 2;</code>
   */
  int getMaxByteSize(int index);
}
