/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boosted_trees.proto

package org.tensorflow.framework;

public interface GrowingMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.boosted_trees.GrowingMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of trees that we have attempted to build. After pruning, these
   * trees might have been removed.
   * </pre>
   *
   * <code>int64 num_trees_attempted = 1;</code>
   */
  long getNumTreesAttempted();

  /**
   * <pre>
   * Number of layers that we have attempted to build. After pruning, these
   * layers might have been removed.
   * </pre>
   *
   * <code>int64 num_layers_attempted = 2;</code>
   */
  long getNumLayersAttempted();

  /**
   * <pre>
   * The start (inclusive) and end (exclusive) ids of the nodes in the latest
   * layer of the latest tree.
   * </pre>
   *
   * <code>int32 last_layer_node_start = 3;</code>
   */
  int getLastLayerNodeStart();

  /**
   * <code>int32 last_layer_node_end = 4;</code>
   */
  int getLastLayerNodeEnd();
}
