/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boosted_trees.proto

package org.tensorflow.framework;

public interface LeafOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.boosted_trees.Leaf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * See third_party/tensorflow/contrib/decision_trees/
   * proto/generic_tree_model.proto
   * for a description of how vector and sparse_vector might be used.
   * </pre>
   *
   * <code>.tensorflow.boosted_trees.Vector vector = 1;</code>
   */
  boolean hasVector();
  /**
   * <pre>
   * See third_party/tensorflow/contrib/decision_trees/
   * proto/generic_tree_model.proto
   * for a description of how vector and sparse_vector might be used.
   * </pre>
   *
   * <code>.tensorflow.boosted_trees.Vector vector = 1;</code>
   */
  org.tensorflow.framework.Vector getVector();
  /**
   * <pre>
   * See third_party/tensorflow/contrib/decision_trees/
   * proto/generic_tree_model.proto
   * for a description of how vector and sparse_vector might be used.
   * </pre>
   *
   * <code>.tensorflow.boosted_trees.Vector vector = 1;</code>
   */
  org.tensorflow.framework.VectorOrBuilder getVectorOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.SparseVector sparse_vector = 2;</code>
   */
  boolean hasSparseVector();
  /**
   * <code>.tensorflow.boosted_trees.SparseVector sparse_vector = 2;</code>
   */
  org.tensorflow.framework.SparseVector getSparseVector();
  /**
   * <code>.tensorflow.boosted_trees.SparseVector sparse_vector = 2;</code>
   */
  org.tensorflow.framework.SparseVectorOrBuilder getSparseVectorOrBuilder();

  /**
   * <code>float scalar = 3;</code>
   */
  float getScalar();

  org.tensorflow.framework.Leaf.LeafCase getLeafCase();
}
