/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attr_value.proto

package org.tensorflow.framework;

public interface NameAttrListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.NameAttrList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 2;</code>
   */
  int getAttrCount();
  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 2;</code>
   */
  boolean containsAttr(
      java.lang.String key);
  /**
   * Use {@link #getAttrMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue>
  getAttr();
  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 2;</code>
   */
  java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue>
  getAttrMap();
  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 2;</code>
   */

  org.tensorflow.framework.AttrValue getAttrOrDefault(
      java.lang.String key,
      org.tensorflow.framework.AttrValue defaultValue);
  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 2;</code>
   */

  org.tensorflow.framework.AttrValue getAttrOrThrow(
      java.lang.String key);
}
