/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boosted_trees.proto

package org.tensorflow.framework;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.boosted_trees.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.boosted_trees.Leaf leaf = 1;</code>
   */
  boolean hasLeaf();
  /**
   * <code>.tensorflow.boosted_trees.Leaf leaf = 1;</code>
   */
  org.tensorflow.framework.Leaf getLeaf();
  /**
   * <code>.tensorflow.boosted_trees.Leaf leaf = 1;</code>
   */
  org.tensorflow.framework.LeafOrBuilder getLeafOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.BucketizedSplit bucketized_split = 2;</code>
   */
  boolean hasBucketizedSplit();
  /**
   * <code>.tensorflow.boosted_trees.BucketizedSplit bucketized_split = 2;</code>
   */
  org.tensorflow.framework.BucketizedSplit getBucketizedSplit();
  /**
   * <code>.tensorflow.boosted_trees.BucketizedSplit bucketized_split = 2;</code>
   */
  org.tensorflow.framework.BucketizedSplitOrBuilder getBucketizedSplitOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.CategoricalSplit categorical_split = 3;</code>
   */
  boolean hasCategoricalSplit();
  /**
   * <code>.tensorflow.boosted_trees.CategoricalSplit categorical_split = 3;</code>
   */
  org.tensorflow.framework.CategoricalSplit getCategoricalSplit();
  /**
   * <code>.tensorflow.boosted_trees.CategoricalSplit categorical_split = 3;</code>
   */
  org.tensorflow.framework.CategoricalSplitOrBuilder getCategoricalSplitOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.DenseSplit dense_split = 4;</code>
   */
  boolean hasDenseSplit();
  /**
   * <code>.tensorflow.boosted_trees.DenseSplit dense_split = 4;</code>
   */
  org.tensorflow.framework.DenseSplit getDenseSplit();
  /**
   * <code>.tensorflow.boosted_trees.DenseSplit dense_split = 4;</code>
   */
  org.tensorflow.framework.DenseSplitOrBuilder getDenseSplitOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  boolean hasMetadata();
  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  org.tensorflow.framework.NodeMetadata getMetadata();
  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  org.tensorflow.framework.NodeMetadataOrBuilder getMetadataOrBuilder();

  org.tensorflow.framework.Node.NodeCase getNodeCase();
}
