/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: saved_model.proto

package org.tensorflow.framework;

public final class SavedModelProtos {
  private SavedModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SavedModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SavedModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021saved_model.proto\022\ntensorflow\032)tensorf" +
      "low/core/protobuf/meta_graph.proto\"_\n\nSa" +
      "vedModel\022\"\n\032saved_model_schema_version\030\001" +
      " \001(\003\022-\n\013meta_graphs\030\002 \003(\0132\030.tensorflow.M" +
      "etaGraphDefBo\n\030org.tensorflow.frameworkB" +
      "\020SavedModelProtosP\001Z<github.com/tensorfl" +
      "ow/tensorflow/tensorflow/go/core/protobu" +
      "f\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.MetaGraphProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_SavedModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_SavedModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SavedModel_descriptor,
        new java.lang.String[] { "SavedModelSchemaVersion", "MetaGraphs", });
    org.tensorflow.framework.MetaGraphProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
