// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: step_stats.proto

package org.tensorflow.framework;

public final class StepStatsProtos {
  private StepStatsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AllocationRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AllocationRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AllocatorMemoryUsed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AllocatorMemoryUsed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MemoryStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MemoryStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NodeExecStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NodeExecStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeviceStepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeviceStepStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_StepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_StepStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020step_stats.proto\022\ntensorflow\0326tensorfl" +
      "ow/core/framework/allocation_description" +
      ".proto\0322tensorflow/core/framework/tensor" +
      "_description.proto\"=\n\020AllocationRecord\022\024" +
      "\n\014alloc_micros\030\001 \001(\003\022\023\n\013alloc_bytes\030\002 \001(" +
      "\003\"\304\001\n\023AllocatorMemoryUsed\022\026\n\016allocator_n" +
      "ame\030\001 \001(\t\022\023\n\013total_bytes\030\002 \001(\003\022\022\n\npeak_b" +
      "ytes\030\003 \001(\003\022\022\n\nlive_bytes\030\004 \001(\003\0228\n\022alloca" +
      "tion_records\030\006 \003(\0132\034.tensorflow.Allocati" +
      "onRecord\022\036\n\026allocator_bytes_in_use\030\005 \001(\003" +
      "\"U\n\nNodeOutput\022\014\n\004slot\030\001 \001(\005\0229\n\022tensor_d" +
      "escription\030\003 \001(\0132\035.tensorflow.TensorDesc" +
      "ription\"\354\001\n\013MemoryStats\022\030\n\020temp_memory_s" +
      "ize\030\001 \001(\003\022\036\n\026persistent_memory_size\030\003 \001(" +
      "\003\022#\n\033persistent_tensor_alloc_ids\030\005 \003(\003\022#" +
      "\n\027device_temp_memory_size\030\002 \001(\003B\002\030\001\022)\n\035d" +
      "evice_persistent_memory_size\030\004 \001(\003B\002\030\001\022." +
      "\n\"device_persistent_tensor_alloc_ids\030\006 \003" +
      "(\003B\002\030\001\"\236\004\n\rNodeExecStats\022\021\n\tnode_name\030\001 " +
      "\001(\t\022\030\n\020all_start_micros\030\002 \001(\003\022\033\n\023op_star" +
      "t_rel_micros\030\003 \001(\003\022\031\n\021op_end_rel_micros\030" +
      "\004 \001(\003\022\032\n\022all_end_rel_micros\030\005 \001(\003\022/\n\006mem" +
      "ory\030\006 \003(\0132\037.tensorflow.AllocatorMemoryUs" +
      "ed\022&\n\006output\030\007 \003(\0132\026.tensorflow.NodeOutp" +
      "ut\022\026\n\016timeline_label\030\010 \001(\t\022\030\n\020scheduled_" +
      "micros\030\t \001(\003\022\021\n\tthread_id\030\n \001(\r\022<\n\021refer" +
      "enced_tensor\030\013 \003(\0132!.tensorflow.Allocati" +
      "onDescription\022-\n\014memory_stats\030\014 \001(\0132\027.te" +
      "nsorflow.MemoryStats\022\027\n\017all_start_nanos\030" +
      "\r \001(\003\022\032\n\022op_start_rel_nanos\030\016 \001(\003\022\030\n\020op_" +
      "end_rel_nanos\030\017 \001(\003\022\031\n\021all_end_rel_nanos" +
      "\030\020 \001(\003\022\027\n\017scheduled_nanos\030\021 \001(\003\"P\n\017Devic" +
      "eStepStats\022\016\n\006device\030\001 \001(\t\022-\n\nnode_stats" +
      "\030\002 \003(\0132\031.tensorflow.NodeExecStats\";\n\tSte" +
      "pStats\022.\n\tdev_stats\030\001 \003(\0132\033.tensorflow.D" +
      "eviceStepStatsBo\n\030org.tensorflow.framewo" +
      "rkB\017StepStatsProtosP\001Z=github.com/tensor" +
      "flow/tensorflow/tensorflow/go/core/frame" +
      "work\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.AllocationDescriptionProtos.getDescriptor(),
          org.tensorflow.framework.TensorDescriptionProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_AllocationRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_AllocationRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AllocationRecord_descriptor,
        new java.lang.String[] { "AllocMicros", "AllocBytes", });
    internal_static_tensorflow_AllocatorMemoryUsed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_AllocatorMemoryUsed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AllocatorMemoryUsed_descriptor,
        new java.lang.String[] { "AllocatorName", "TotalBytes", "PeakBytes", "LiveBytes", "AllocationRecords", "AllocatorBytesInUse", });
    internal_static_tensorflow_NodeOutput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_NodeOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeOutput_descriptor,
        new java.lang.String[] { "Slot", "TensorDescription", });
    internal_static_tensorflow_MemoryStats_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_MemoryStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MemoryStats_descriptor,
        new java.lang.String[] { "TempMemorySize", "PersistentMemorySize", "PersistentTensorAllocIds", "DeviceTempMemorySize", "DevicePersistentMemorySize", "DevicePersistentTensorAllocIds", });
    internal_static_tensorflow_NodeExecStats_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_NodeExecStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NodeExecStats_descriptor,
        new java.lang.String[] { "NodeName", "AllStartMicros", "OpStartRelMicros", "OpEndRelMicros", "AllEndRelMicros", "Memory", "Output", "TimelineLabel", "ScheduledMicros", "ThreadId", "ReferencedTensor", "MemoryStats", "AllStartNanos", "OpStartRelNanos", "OpEndRelNanos", "AllEndRelNanos", "ScheduledNanos", });
    internal_static_tensorflow_DeviceStepStats_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_DeviceStepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeviceStepStats_descriptor,
        new java.lang.String[] { "Device", "NodeStats", });
    internal_static_tensorflow_StepStats_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_StepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_StepStats_descriptor,
        new java.lang.String[] { "DevStats", });
    org.tensorflow.framework.AllocationDescriptionProtos.getDescriptor();
    org.tensorflow.framework.TensorDescriptionProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
