/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: step_stats.proto

package org.tensorflow.framework;

public interface StepStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.StepStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.DeviceStepStats dev_stats = 1;</code>
   */
  java.util.List<org.tensorflow.framework.DeviceStepStats> 
      getDevStatsList();
  /**
   * <code>repeated .tensorflow.DeviceStepStats dev_stats = 1;</code>
   */
  org.tensorflow.framework.DeviceStepStats getDevStats(int index);
  /**
   * <code>repeated .tensorflow.DeviceStepStats dev_stats = 1;</code>
   */
  int getDevStatsCount();
  /**
   * <code>repeated .tensorflow.DeviceStepStats dev_stats = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.DeviceStepStatsOrBuilder> 
      getDevStatsOrBuilderList();
  /**
   * <code>repeated .tensorflow.DeviceStepStats dev_stats = 1;</code>
   */
  org.tensorflow.framework.DeviceStepStatsOrBuilder getDevStatsOrBuilder(
      int index);
}
