/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package org.tensorflow.framework;

public interface SummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Summary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Set of values for the summary.
   * </pre>
   *
   * <code>repeated .tensorflow.Summary.Value value = 1;</code>
   */
  java.util.List<org.tensorflow.framework.Summary.Value> 
      getValueList();
  /**
   * <pre>
   * Set of values for the summary.
   * </pre>
   *
   * <code>repeated .tensorflow.Summary.Value value = 1;</code>
   */
  org.tensorflow.framework.Summary.Value getValue(int index);
  /**
   * <pre>
   * Set of values for the summary.
   * </pre>
   *
   * <code>repeated .tensorflow.Summary.Value value = 1;</code>
   */
  int getValueCount();
  /**
   * <pre>
   * Set of values for the summary.
   * </pre>
   *
   * <code>repeated .tensorflow.Summary.Value value = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.Summary.ValueOrBuilder> 
      getValueOrBuilderList();
  /**
   * <pre>
   * Set of values for the summary.
   * </pre>
   *
   * <code>repeated .tensorflow.Summary.Value value = 1;</code>
   */
  org.tensorflow.framework.Summary.ValueOrBuilder getValueOrBuilder(
      int index);
}
