/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_flow.proto

package org.tensorflow.framework;

public interface ValuesDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ValuesDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Value names that have been seen in this context.
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <pre>
   * Value names that have been seen in this context.
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   */
  int getValuesCount();
  /**
   * <pre>
   * Value names that have been seen in this context.
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   */
  java.lang.String getValues(int index);
  /**
   * <pre>
   * Value names that have been seen in this context.
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);

  /**
   * <pre>
   * Value names referenced by but external to this context.
   * </pre>
   *
   * <code>map&lt;string, string&gt; external_values = 2;</code>
   */
  int getExternalValuesCount();
  /**
   * <pre>
   * Value names referenced by but external to this context.
   * </pre>
   *
   * <code>map&lt;string, string&gt; external_values = 2;</code>
   */
  boolean containsExternalValues(
      java.lang.String key);
  /**
   * Use {@link #getExternalValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExternalValues();
  /**
   * <pre>
   * Value names referenced by but external to this context.
   * </pre>
   *
   * <code>map&lt;string, string&gt; external_values = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExternalValuesMap();
  /**
   * <pre>
   * Value names referenced by but external to this context.
   * </pre>
   *
   * <code>map&lt;string, string&gt; external_values = 2;</code>
   */

  java.lang.String getExternalValuesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * Value names referenced by but external to this context.
   * </pre>
   *
   * <code>map&lt;string, string&gt; external_values = 2;</code>
   */

  java.lang.String getExternalValuesOrThrow(
      java.lang.String key);
}
