/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verbs_service.proto

package org.tensorflow.contrib.verbs;

public interface ChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Channel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lid = 1;</code>
   */
  int getLid();

  /**
   * <code>int32 qpn = 2;</code>
   */
  int getQpn();

  /**
   * <code>int32 psn = 3;</code>
   */
  int getPsn();

  /**
   * <code>uint64 snp = 4;</code>
   */
  long getSnp();

  /**
   * <code>uint64 iid = 5;</code>
   */
  long getIid();
}
