/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verbs_service.proto

package org.tensorflow.contrib.verbs;

public interface GetRemoteAddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GetRemoteAddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host_name = 1;</code>
   */
  java.lang.String getHostName();
  /**
   * <code>string host_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  boolean hasChannel();
  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  org.tensorflow.contrib.verbs.Channel getChannel();
  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  org.tensorflow.contrib.verbs.ChannelOrBuilder getChannelOrBuilder();

  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  java.util.List<org.tensorflow.contrib.verbs.MemoryRegion> 
      getMrList();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  org.tensorflow.contrib.verbs.MemoryRegion getMr(int index);
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  int getMrCount();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  java.util.List<? extends org.tensorflow.contrib.verbs.MemoryRegionOrBuilder> 
      getMrOrBuilderList();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  org.tensorflow.contrib.verbs.MemoryRegionOrBuilder getMrOrBuilder(
      int index);
}
