/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verbs_service.proto

package org.tensorflow.contrib.verbs;

public final class VerbsServiceProtos {
  private VerbsServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_Channel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_Channel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MemoryRegion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MemoryRegion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetRemoteAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetRemoteAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetRemoteAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetRemoteAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ErrorStatusProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ErrorStatusProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023verbs_service.proto\022\ntensorflow\"J\n\007Cha" +
      "nnel\022\013\n\003lid\030\001 \001(\005\022\013\n\003qpn\030\002 \001(\005\022\013\n\003psn\030\003 " +
      "\001(\005\022\013\n\003snp\030\004 \001(\004\022\013\n\003iid\030\005 \001(\004\"1\n\014MemoryR" +
      "egion\022\023\n\013remote_addr\030\001 \001(\004\022\014\n\004rkey\030\002 \001(\r" +
      "\"x\n\027GetRemoteAddressRequest\022\021\n\thost_name" +
      "\030\001 \001(\t\022$\n\007channel\030\002 \001(\0132\023.tensorflow.Cha" +
      "nnel\022$\n\002mr\030\003 \003(\0132\030.tensorflow.MemoryRegi" +
      "on\"y\n\030GetRemoteAddressResponse\022\021\n\thost_n" +
      "ame\030\001 \001(\t\022$\n\007channel\030\002 \001(\0132\023.tensorflow." +
      "Channel\022$\n\002mr\030\003 \003(\0132\030.tensorflow.MemoryR" +
      "egion\"T\n\020ErrorStatusProto\022\022\n\nerror_code\030" +
      "\001 \001(\005\022\025\n\rerror_message\030\002 \001(\t\022\025\n\rerror_de" +
      "tails\030\003 \001(\t2m\n\014VerbsService\022]\n\020GetRemote" +
      "Address\022#.tensorflow.GetRemoteAddressReq" +
      "uest\032$.tensorflow.GetRemoteAddressRespon" +
      "seB4\n\034org.tensorflow.contrib.verbsB\022Verb" +
      "sServiceProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_Channel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_Channel_descriptor,
        new java.lang.String[] { "Lid", "Qpn", "Psn", "Snp", "Iid", });
    internal_static_tensorflow_MemoryRegion_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_MemoryRegion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MemoryRegion_descriptor,
        new java.lang.String[] { "RemoteAddr", "Rkey", });
    internal_static_tensorflow_GetRemoteAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_GetRemoteAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetRemoteAddressRequest_descriptor,
        new java.lang.String[] { "HostName", "Channel", "Mr", });
    internal_static_tensorflow_GetRemoteAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_GetRemoteAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetRemoteAddressResponse_descriptor,
        new java.lang.String[] { "HostName", "Channel", "Mr", });
    internal_static_tensorflow_ErrorStatusProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_ErrorStatusProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ErrorStatusProto_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "ErrorDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
