/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface CompleteGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CompleteGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 group_key = 1;</code>
   */
  int getGroupKey();

  /**
   * <code>int32 group_size = 2;</code>
   */
  int getGroupSize();

  /**
   * <code>string device_type = 3;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <code>string device_type = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <pre>
   * number of distinct tasks hosting the devices
   * </pre>
   *
   * <code>int32 num_tasks = 4;</code>
   */
  int getNumTasks();

  /**
   * <code>repeated string device_name = 5;</code>
   */
  java.util.List<java.lang.String>
      getDeviceNameList();
  /**
   * <code>repeated string device_name = 5;</code>
   */
  int getDeviceNameCount();
  /**
   * <code>repeated string device_name = 5;</code>
   */
  java.lang.String getDeviceName(int index);
  /**
   * <code>repeated string device_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes(int index);

  /**
   * <pre>
   * task name prefixes of device_names
   * </pre>
   *
   * <code>repeated string task_name = 6;</code>
   */
  java.util.List<java.lang.String>
      getTaskNameList();
  /**
   * <pre>
   * task name prefixes of device_names
   * </pre>
   *
   * <code>repeated string task_name = 6;</code>
   */
  int getTaskNameCount();
  /**
   * <pre>
   * task name prefixes of device_names
   * </pre>
   *
   * <code>repeated string task_name = 6;</code>
   */
  java.lang.String getTaskName(int index);
  /**
   * <pre>
   * task name prefixes of device_names
   * </pre>
   *
   * <code>repeated string task_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getTaskNameBytes(int index);
}
