/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface CompleteInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CompleteInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 type = 2;</code>
   */
  int getType();

  /**
   * <code>.tensorflow.DataType data_type = 3;</code>
   */
  int getDataTypeValue();
  /**
   * <code>.tensorflow.DataType data_type = 3;</code>
   */
  org.tensorflow.framework.DataType getDataType();

  /**
   * <code>.tensorflow.TensorShapeProto shape = 4;</code>
   */
  boolean hasShape();
  /**
   * <code>.tensorflow.TensorShapeProto shape = 4;</code>
   */
  org.tensorflow.framework.TensorShapeProto getShape();
  /**
   * <code>.tensorflow.TensorShapeProto shape = 4;</code>
   */
  org.tensorflow.framework.TensorShapeProtoOrBuilder getShapeOrBuilder();

  /**
   * <code>int32 group_key = 5;</code>
   */
  int getGroupKey();

  /**
   * <code>int32 group_size = 6;</code>
   */
  int getGroupSize();

  /**
   * <code>int32 instance_key = 7;</code>
   */
  int getInstanceKey();

  /**
   * <code>string device_type = 8;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <code>string device_type = 8;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>repeated int32 subdiv_offset = 9;</code>
   */
  java.util.List<java.lang.Integer> getSubdivOffsetList();
  /**
   * <code>repeated int32 subdiv_offset = 9;</code>
   */
  int getSubdivOffsetCount();
  /**
   * <code>repeated int32 subdiv_offset = 9;</code>
   */
  int getSubdivOffset(int index);

  /**
   * <code>string device = 10;</code>
   */
  java.lang.String getDevice();
  /**
   * <code>string device = 10;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>bool is_source = 11;</code>
   */
  boolean getIsSource();
}
