/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package org.tensorflow.distruntime;

public final class DistributedRuntimeProtos {
  private DistributedRuntimeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExtendSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExtendSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExtendSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExtendSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunStepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunStepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_PartialRunSetupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_PartialRunSetupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_PartialRunSetupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_PartialRunSetupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CloseSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CloseSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CloseSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CloseSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ResetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ResetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ResetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ResetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ListDevicesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ListDevicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ListDevicesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ListDevicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MakeCallableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MakeCallableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MakeCallableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MakeCallableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunCallableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunCallableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunCallableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunCallableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ReleaseCallableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ReleaseCallableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ReleaseCallableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ReleaseCallableResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014master.proto\022\ntensorflow\0321tensorflow/c" +
      "ore/framework/device_attributes.proto\032%t" +
      "ensorflow/core/framework/graph.proto\032&te" +
      "nsorflow/core/framework/tensor.proto\032*te" +
      "nsorflow/core/lib/core/error_codes.proto" +
      "\032%tensorflow/core/protobuf/config.proto\032" +
      "+tensorflow/core/protobuf/named_tensor.p" +
      "roto\"x\n\024CreateSessionRequest\022\'\n\tgraph_de" +
      "f\030\001 \001(\0132\024.tensorflow.GraphDef\022\'\n\006config\030" +
      "\002 \001(\0132\027.tensorflow.ConfigProto\022\016\n\006target" +
      "\030\003 \001(\t\"F\n\025CreateSessionResponse\022\026\n\016sessi" +
      "on_handle\030\001 \001(\t\022\025\n\rgraph_version\030\002 \001(\003\"v" +
      "\n\024ExtendSessionRequest\022\026\n\016session_handle" +
      "\030\001 \001(\t\022\'\n\tgraph_def\030\002 \001(\0132\024.tensorflow.G" +
      "raphDef\022\035\n\025current_graph_version\030\003 \001(\003\"2" +
      "\n\025ExtendSessionResponse\022\031\n\021new_graph_ver" +
      "sion\030\004 \001(\003\"\337\001\n\016RunStepRequest\022\026\n\016session" +
      "_handle\030\001 \001(\t\022*\n\004feed\030\002 \003(\0132\034.tensorflow" +
      ".NamedTensorProto\022\r\n\005fetch\030\003 \003(\t\022\016\n\006targ" +
      "et\030\004 \003(\t\022\'\n\007options\030\005 \001(\0132\026.tensorflow.R" +
      "unOptions\022\032\n\022partial_run_handle\030\006 \001(\t\022%\n" +
      "\035store_errors_in_response_body\030\007 \001(\010\"\265\001\n" +
      "\017RunStepResponse\022,\n\006tensor\030\001 \003(\0132\034.tenso" +
      "rflow.NamedTensorProto\022)\n\010metadata\030\002 \001(\013" +
      "2\027.tensorflow.RunMetadata\022+\n\013status_code" +
      "\030\003 \001(\0162\026.tensorflow.error.Code\022\034\n\024status" +
      "_error_message\030\004 \001(\t\"]\n\026PartialRunSetupR" +
      "equest\022\026\n\016session_handle\030\001 \001(\t\022\014\n\004feed\030\002" +
      " \003(\t\022\r\n\005fetch\030\003 \003(\t\022\016\n\006target\030\004 \003(\t\"5\n\027P" +
      "artialRunSetupResponse\022\032\n\022partial_run_ha" +
      "ndle\030\001 \001(\t\"-\n\023CloseSessionRequest\022\026\n\016ses" +
      "sion_handle\030\001 \001(\t\"\026\n\024CloseSessionRespons" +
      "e\"9\n\014ResetRequest\022\021\n\tcontainer\030\001 \003(\t\022\026\n\016" +
      "device_filters\030\002 \003(\t\"\017\n\rResetResponse\",\n" +
      "\022ListDevicesRequest\022\026\n\016session_handle\030\001 " +
      "\001(\t\"~\n\023ListDevicesResponse\0222\n\014local_devi" +
      "ce\030\001 \003(\0132\034.tensorflow.DeviceAttributes\0223" +
      "\n\rremote_device\030\002 \003(\0132\034.tensorflow.Devic" +
      "eAttributes\"[\n\023MakeCallableRequest\022\026\n\016se" +
      "ssion_handle\030\001 \001(\t\022,\n\007options\030\002 \001(\0132\033.te" +
      "nsorflow.CallableOptions\"&\n\024MakeCallable" +
      "Response\022\016\n\006handle\030\001 \001(\003\"c\n\022RunCallableR" +
      "equest\022\026\n\016session_handle\030\001 \001(\t\022\016\n\006handle" +
      "\030\002 \001(\003\022%\n\004feed\030\003 \003(\0132\027.tensorflow.Tensor" +
      "Proto\"h\n\023RunCallableResponse\022&\n\005fetch\030\001 " +
      "\003(\0132\027.tensorflow.TensorProto\022)\n\010metadata" +
      "\030\002 \001(\0132\027.tensorflow.RunMetadata\"@\n\026Relea" +
      "seCallableRequest\022\026\n\016session_handle\030\001 \001(" +
      "\t\022\016\n\006handle\030\002 \001(\003\"\031\n\027ReleaseCallableResp" +
      "onseBy\n\032org.tensorflow.distruntimeB\030Dist" +
      "ributedRuntimeProtosP\001Z<github.com/tenso" +
      "rflow/tensorflow/tensorflow/go/core/prot" +
      "obuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.DeviceAttributesProtos.getDescriptor(),
          org.tensorflow.framework.GraphProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.ErrorCodesProtos.getDescriptor(),
          org.tensorflow.framework.ConfigProtos.getDescriptor(),
          org.tensorflow.framework.NamedTensorProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_CreateSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_CreateSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateSessionRequest_descriptor,
        new java.lang.String[] { "GraphDef", "Config", "Target", });
    internal_static_tensorflow_CreateSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_CreateSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateSessionResponse_descriptor,
        new java.lang.String[] { "SessionHandle", "GraphVersion", });
    internal_static_tensorflow_ExtendSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_ExtendSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExtendSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "GraphDef", "CurrentGraphVersion", });
    internal_static_tensorflow_ExtendSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_ExtendSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExtendSessionResponse_descriptor,
        new java.lang.String[] { "NewGraphVersion", });
    internal_static_tensorflow_RunStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_RunStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunStepRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "Feed", "Fetch", "Target", "Options", "PartialRunHandle", "StoreErrorsInResponseBody", });
    internal_static_tensorflow_RunStepResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_RunStepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunStepResponse_descriptor,
        new java.lang.String[] { "Tensor", "Metadata", "StatusCode", "StatusErrorMessage", });
    internal_static_tensorflow_PartialRunSetupRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_PartialRunSetupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_PartialRunSetupRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "Feed", "Fetch", "Target", });
    internal_static_tensorflow_PartialRunSetupResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tensorflow_PartialRunSetupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_PartialRunSetupResponse_descriptor,
        new java.lang.String[] { "PartialRunHandle", });
    internal_static_tensorflow_CloseSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tensorflow_CloseSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CloseSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", });
    internal_static_tensorflow_CloseSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tensorflow_CloseSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CloseSessionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_ResetRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tensorflow_ResetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ResetRequest_descriptor,
        new java.lang.String[] { "Container", "DeviceFilters", });
    internal_static_tensorflow_ResetResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tensorflow_ResetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ResetResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_ListDevicesRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tensorflow_ListDevicesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ListDevicesRequest_descriptor,
        new java.lang.String[] { "SessionHandle", });
    internal_static_tensorflow_ListDevicesResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tensorflow_ListDevicesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ListDevicesResponse_descriptor,
        new java.lang.String[] { "LocalDevice", "RemoteDevice", });
    internal_static_tensorflow_MakeCallableRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tensorflow_MakeCallableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MakeCallableRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "Options", });
    internal_static_tensorflow_MakeCallableResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tensorflow_MakeCallableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MakeCallableResponse_descriptor,
        new java.lang.String[] { "Handle", });
    internal_static_tensorflow_RunCallableRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tensorflow_RunCallableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunCallableRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "Handle", "Feed", });
    internal_static_tensorflow_RunCallableResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tensorflow_RunCallableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunCallableResponse_descriptor,
        new java.lang.String[] { "Fetch", "Metadata", });
    internal_static_tensorflow_ReleaseCallableRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_tensorflow_ReleaseCallableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ReleaseCallableRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "Handle", });
    internal_static_tensorflow_ReleaseCallableResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_tensorflow_ReleaseCallableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ReleaseCallableResponse_descriptor,
        new java.lang.String[] { });
    org.tensorflow.framework.DeviceAttributesProtos.getDescriptor();
    org.tensorflow.framework.GraphProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.ErrorCodesProtos.getDescriptor();
    org.tensorflow.framework.ConfigProtos.getDescriptor();
    org.tensorflow.framework.NamedTensorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
