/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface ExecutorOptsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ExecutorOpts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool record_costs = 1;</code>
   */
  boolean getRecordCosts();

  /**
   * <code>bool record_timeline = 3;</code>
   */
  boolean getRecordTimeline();

  /**
   * <code>bool record_partition_graphs = 4;</code>
   */
  boolean getRecordPartitionGraphs();

  /**
   * <code>bool report_tensor_allocations_upon_oom = 5;</code>
   */
  boolean getReportTensorAllocationsUponOom();
}
