/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface LabeledStepStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.LabeledStepStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 step_id = 1;</code>
   */
  long getStepId();

  /**
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  boolean hasStepStats();
  /**
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStats getStepStats();
  /**
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder();
}
