/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package org.tensorflow.distruntime;

public interface ListDevicesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ListDevicesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.DeviceAttributes local_device = 1;</code>
   */
  java.util.List<org.tensorflow.framework.DeviceAttributes> 
      getLocalDeviceList();
  /**
   * <code>repeated .tensorflow.DeviceAttributes local_device = 1;</code>
   */
  org.tensorflow.framework.DeviceAttributes getLocalDevice(int index);
  /**
   * <code>repeated .tensorflow.DeviceAttributes local_device = 1;</code>
   */
  int getLocalDeviceCount();
  /**
   * <code>repeated .tensorflow.DeviceAttributes local_device = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.DeviceAttributesOrBuilder> 
      getLocalDeviceOrBuilderList();
  /**
   * <code>repeated .tensorflow.DeviceAttributes local_device = 1;</code>
   */
  org.tensorflow.framework.DeviceAttributesOrBuilder getLocalDeviceOrBuilder(
      int index);

  /**
   * <code>repeated .tensorflow.DeviceAttributes remote_device = 2;</code>
   */
  java.util.List<org.tensorflow.framework.DeviceAttributes> 
      getRemoteDeviceList();
  /**
   * <code>repeated .tensorflow.DeviceAttributes remote_device = 2;</code>
   */
  org.tensorflow.framework.DeviceAttributes getRemoteDevice(int index);
  /**
   * <code>repeated .tensorflow.DeviceAttributes remote_device = 2;</code>
   */
  int getRemoteDeviceCount();
  /**
   * <code>repeated .tensorflow.DeviceAttributes remote_device = 2;</code>
   */
  java.util.List<? extends org.tensorflow.framework.DeviceAttributesOrBuilder> 
      getRemoteDeviceOrBuilderList();
  /**
   * <code>repeated .tensorflow.DeviceAttributes remote_device = 2;</code>
   */
  org.tensorflow.framework.DeviceAttributesOrBuilder getRemoteDeviceOrBuilder(
      int index);
}
