/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface LoggingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.LoggingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If true, RPC logging will be enabled.
   * </pre>
   *
   * <code>bool enable_rpc_logging = 1;</code>
   */
  boolean getEnableRpcLogging();

  /**
   * <pre>
   * If true, RPC logging will be disabled.
   * </pre>
   *
   * <code>bool disable_rpc_logging = 4;</code>
   */
  boolean getDisableRpcLogging();

  /**
   * <pre>
   * If true, discard any saved logging data (for all steps).
   * </pre>
   *
   * <code>bool clear = 2;</code>
   */
  boolean getClear();

  /**
   * <pre>
   * When set, requests all saved log data pertaining to the step.
   * Any log data retrieved is eliminated from the store and cannot be
   * retrieved again.
   * </pre>
   *
   * <code>repeated int64 fetch_step_id = 3;</code>
   */
  java.util.List<java.lang.Long> getFetchStepIdList();
  /**
   * <pre>
   * When set, requests all saved log data pertaining to the step.
   * Any log data retrieved is eliminated from the store and cannot be
   * retrieved again.
   * </pre>
   *
   * <code>repeated int64 fetch_step_id = 3;</code>
   */
  int getFetchStepIdCount();
  /**
   * <pre>
   * When set, requests all saved log data pertaining to the step.
   * Any log data retrieved is eliminated from the store and cannot be
   * retrieved again.
   * </pre>
   *
   * <code>repeated int64 fetch_step_id = 3;</code>
   */
  long getFetchStepId(int index);
}
