/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface LoggingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.LoggingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.LabeledStepStats step = 1;</code>
   */
  java.util.List<org.tensorflow.distruntime.LabeledStepStats> 
      getStepList();
  /**
   * <code>repeated .tensorflow.LabeledStepStats step = 1;</code>
   */
  org.tensorflow.distruntime.LabeledStepStats getStep(int index);
  /**
   * <code>repeated .tensorflow.LabeledStepStats step = 1;</code>
   */
  int getStepCount();
  /**
   * <code>repeated .tensorflow.LabeledStepStats step = 1;</code>
   */
  java.util.List<? extends org.tensorflow.distruntime.LabeledStepStatsOrBuilder> 
      getStepOrBuilderList();
  /**
   * <code>repeated .tensorflow.LabeledStepStats step = 1;</code>
   */
  org.tensorflow.distruntime.LabeledStepStatsOrBuilder getStepOrBuilder(
      int index);
}
