/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface RecvTensorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RecvTensorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The tensor as a proto.
   * </pre>
   *
   * <code>.tensorflow.TensorProto tensor = 1;</code>
   */
  boolean hasTensor();
  /**
   * <pre>
   * The tensor as a proto.
   * </pre>
   *
   * <code>.tensorflow.TensorProto tensor = 1;</code>
   */
  org.tensorflow.framework.TensorProto getTensor();
  /**
   * <pre>
   * The tensor as a proto.
   * </pre>
   *
   * <code>.tensorflow.TensorProto tensor = 1;</code>
   */
  org.tensorflow.framework.TensorProtoOrBuilder getTensorOrBuilder();

  /**
   * <pre>
   * If true, this tensor was the output of a dead node, and the
   * content is invalid.
   * </pre>
   *
   * <code>bool is_dead = 2;</code>
   */
  boolean getIsDead();

  /**
   * <pre>
   * The time at which tensor was available and started to be returned.
   * </pre>
   *
   * <code>int64 send_start_micros = 3;</code>
   */
  long getSendStartMicros();

  /**
   * <pre>
   * Optional additional information about how to receive the tensor,
   * e.g. in the event that `RecvTensorRequest.dma_ok` was true.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 4;</code>
   */
  boolean hasTransportOptions();
  /**
   * <pre>
   * Optional additional information about how to receive the tensor,
   * e.g. in the event that `RecvTensorRequest.dma_ok` was true.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 4;</code>
   */
  com.google.protobuf.Any getTransportOptions();
  /**
   * <pre>
   * Optional additional information about how to receive the tensor,
   * e.g. in the event that `RecvTensorRequest.dma_ok` was true.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getTransportOptionsOrBuilder();
}
