/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface RegisterGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RegisterGraphResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If the registration succeeds, returns an opaque graph_handle to
   * the master. The master calls RunGraph with graph_handle to
   * compute different steps.
   * </pre>
   *
   * <code>string graph_handle = 1;</code>
   */
  java.lang.String getGraphHandle();
  /**
   * <pre>
   * If the registration succeeds, returns an opaque graph_handle to
   * the master. The master calls RunGraph with graph_handle to
   * compute different steps.
   * </pre>
   *
   * <code>string graph_handle = 1;</code>
   */
  com.google.protobuf.ByteString
      getGraphHandleBytes();
}
