/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package org.tensorflow.distruntime;

public interface RunCallableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunCallableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Values of the tensors returned by the callable, in the order defined in the
   * CallableOptions.fetch field passed to MakeCallable.
   * </pre>
   *
   * <code>repeated .tensorflow.TensorProto fetch = 1;</code>
   */
  java.util.List<org.tensorflow.framework.TensorProto> 
      getFetchList();
  /**
   * <pre>
   * Values of the tensors returned by the callable, in the order defined in the
   * CallableOptions.fetch field passed to MakeCallable.
   * </pre>
   *
   * <code>repeated .tensorflow.TensorProto fetch = 1;</code>
   */
  org.tensorflow.framework.TensorProto getFetch(int index);
  /**
   * <pre>
   * Values of the tensors returned by the callable, in the order defined in the
   * CallableOptions.fetch field passed to MakeCallable.
   * </pre>
   *
   * <code>repeated .tensorflow.TensorProto fetch = 1;</code>
   */
  int getFetchCount();
  /**
   * <pre>
   * Values of the tensors returned by the callable, in the order defined in the
   * CallableOptions.fetch field passed to MakeCallable.
   * </pre>
   *
   * <code>repeated .tensorflow.TensorProto fetch = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.TensorProtoOrBuilder> 
      getFetchOrBuilderList();
  /**
   * <pre>
   * Values of the tensors returned by the callable, in the order defined in the
   * CallableOptions.fetch field passed to MakeCallable.
   * </pre>
   *
   * <code>repeated .tensorflow.TensorProto fetch = 1;</code>
   */
  org.tensorflow.framework.TensorProtoOrBuilder getFetchOrBuilder(
      int index);

  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>.tensorflow.RunMetadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>.tensorflow.RunMetadata metadata = 2;</code>
   */
  org.tensorflow.framework.RunMetadata getMetadata();
  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>.tensorflow.RunMetadata metadata = 2;</code>
   */
  org.tensorflow.framework.RunMetadataOrBuilder getMetadataOrBuilder();
}
