/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public interface RunGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunGraphResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<org.tensorflow.framework.NamedTensorProto> 
      getRecvList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProto getRecv(int index);
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  int getRecvCount();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getRecvOrBuilderList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProtoOrBuilder getRecvOrBuilder(
      int index);

  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  boolean hasStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStats getStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder();

  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  boolean hasCostGraph();
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  org.tensorflow.framework.CostGraphDef getCostGraph();
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  org.tensorflow.framework.CostGraphDefOrBuilder getCostGraphOrBuilder();

  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<org.tensorflow.framework.GraphDef> 
      getPartitionGraphList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDef getPartitionGraph(int index);
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  int getPartitionGraphCount();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<? extends org.tensorflow.framework.GraphDefOrBuilder> 
      getPartitionGraphOrBuilderList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDefOrBuilder getPartitionGraphOrBuilder(
      int index);

  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   */
  int getStatusCodeValue();
  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   */
  org.tensorflow.framework.Code getStatusCode();

  /**
   * <code>string status_error_message = 6;</code>
   */
  java.lang.String getStatusErrorMessage();
  /**
   * <code>string status_error_message = 6;</code>
   */
  com.google.protobuf.ByteString
      getStatusErrorMessageBytes();
}
