/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.tensorflow.distruntime;

public final class WorkerProtos {
  private WorkerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateWorkerSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateWorkerSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CreateWorkerSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CreateWorkerSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeleteWorkerSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeleteWorkerSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExecutorOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExecutorOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LabeledStepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LabeledStepStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TraceOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TraceOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvBufRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvBufRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvBufResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvBufResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CompleteInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CompleteInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStepSequenceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStepSequenceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_StepSequence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_StepSequence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStepSequenceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStepSequenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\022\ntensorflow\032\031google/proto" +
      "buf/any.proto\032*tensorflow/core/framework" +
      "/cost_graph.proto\032*tensorflow/core/frame" +
      "work/step_stats.proto\0321tensorflow/core/f" +
      "ramework/device_attributes.proto\032%tensor" +
      "flow/core/framework/graph.proto\032&tensorf" +
      "low/core/framework/tensor.proto\032,tensorf" +
      "low/core/framework/tensor_shape.proto\032%t" +
      "ensorflow/core/framework/types.proto\032*te" +
      "nsorflow/core/lib/core/error_codes.proto" +
      "\032%tensorflow/core/protobuf/config.proto\032" +
      "$tensorflow/core/protobuf/debug.proto\032+t" +
      "ensorflow/core/protobuf/named_tensor.pro" +
      "to\0320tensorflow/core/protobuf/tensorflow_" +
      "server.proto\"\022\n\020GetStatusRequest\"L\n\021GetS" +
      "tatusResponse\0227\n\021device_attributes\030\001 \003(\013" +
      "2\034.tensorflow.DeviceAttributes\"~\n\032Create" +
      "WorkerSessionRequest\022\026\n\016session_handle\030\001" +
      " \001(\t\022)\n\nserver_def\030\002 \001(\0132\025.tensorflow.Se" +
      "rverDef\022\035\n\025isolate_session_state\030\003 \001(\010\"\035" +
      "\n\033CreateWorkerSessionResponse\"4\n\032DeleteW" +
      "orkerSessionRequest\022\026\n\016session_handle\030\001 " +
      "\001(\t\"\035\n\033DeleteWorkerSessionResponse\"\233\002\n\024R" +
      "egisterGraphRequest\022\026\n\016session_handle\030\001 " +
      "\001(\t\022$\n\034create_worker_session_called\030\006 \001(" +
      "\010\022\'\n\tgraph_def\030\002 \001(\0132\024.tensorflow.GraphD" +
      "ef\022\034\n\020has_control_flow\030\003 \001(\010B\002\030\001\022/\n\rgrap" +
      "h_options\030\004 \001(\0132\030.tensorflow.GraphOption" +
      "s\022/\n\rdebug_options\030\005 \001(\0132\030.tensorflow.De" +
      "bugOptions\022\034\n\024collective_graph_key\030\007 \001(\003" +
      "\"-\n\025RegisterGraphResponse\022\024\n\014graph_handl" +
      "e\030\001 \001(\t\"l\n\026DeregisterGraphRequest\022\026\n\016ses" +
      "sion_handle\030\002 \001(\t\022$\n\034create_worker_sessi" +
      "on_called\030\003 \001(\010\022\024\n\014graph_handle\030\001 \001(\t\"\031\n" +
      "\027DeregisterGraphResponse\"&\n\021CleanupAllRe" +
      "quest\022\021\n\tcontainer\030\001 \003(\t\"\024\n\022CleanupAllRe" +
      "sponse\"\212\001\n\014ExecutorOpts\022\024\n\014record_costs\030" +
      "\001 \001(\010\022\027\n\017record_timeline\030\003 \001(\010\022\037\n\027record" +
      "_partition_graphs\030\004 \001(\010\022*\n\"report_tensor" +
      "_allocations_upon_oom\030\005 \001(\010\"\271\002\n\017RunGraph" +
      "Request\022\026\n\016session_handle\030\010 \001(\t\022$\n\034creat" +
      "e_worker_session_called\030\n \001(\010\022\024\n\014graph_h" +
      "andle\030\001 \001(\t\022\017\n\007step_id\030\002 \001(\003\022+\n\texec_opt" +
      "s\030\005 \001(\0132\030.tensorflow.ExecutorOpts\022*\n\004sen" +
      "d\030\003 \003(\0132\034.tensorflow.NamedTensorProto\022\020\n" +
      "\010recv_key\030\004 \003(\t\022\022\n\nis_partial\030\006 \001(\010\022\033\n\023i" +
      "s_last_partial_run\030\007 \001(\010\022%\n\035store_errors" +
      "_in_response_body\030\t \001(\010\"\221\002\n\020RunGraphResp" +
      "onse\022*\n\004recv\030\001 \003(\0132\034.tensorflow.NamedTen" +
      "sorProto\022)\n\nstep_stats\030\002 \001(\0132\025.tensorflo" +
      "w.StepStats\022,\n\ncost_graph\030\003 \001(\0132\030.tensor" +
      "flow.CostGraphDef\022-\n\017partition_graph\030\004 \003" +
      "(\0132\024.tensorflow.GraphDef\022+\n\013status_code\030" +
      "\005 \001(\0162\026.tensorflow.error.Code\022\034\n\024status_" +
      "error_message\030\006 \001(\t\"&\n\023CleanupGraphReque" +
      "st\022\017\n\007step_id\030\001 \001(\003\"\026\n\024CleanupGraphRespo" +
      "nse\"\373\001\n\021RecvTensorRequest\022\017\n\007step_id\030\001 \001" +
      "(\003\022\026\n\016rendezvous_key\030\002 \001(\t\022\016\n\006dma_ok\030\003 \001" +
      "(\010\0223\n\017client_locality\030\004 \001(\0132\032.tensorflow" +
      ".DeviceLocality\0223\n\017server_locality\030\005 \001(\013" +
      "2\032.tensorflow.DeviceLocality\022/\n\021transpor" +
      "t_options\030\006 \001(\0132\024.google.protobuf.Any\022\022\n" +
      "\nrequest_id\030\007 \001(\003\"\232\001\n\022RecvTensorResponse" +
      "\022\'\n\006tensor\030\001 \001(\0132\027.tensorflow.TensorProt" +
      "o\022\017\n\007is_dead\030\002 \001(\010\022\031\n\021send_start_micros\030" +
      "\003 \001(\003\022/\n\021transport_options\030\004 \001(\0132\024.googl" +
      "e.protobuf.Any\"o\n\016LoggingRequest\022\032\n\022enab" +
      "le_rpc_logging\030\001 \001(\010\022\033\n\023disable_rpc_logg" +
      "ing\030\004 \001(\010\022\r\n\005clear\030\002 \001(\010\022\025\n\rfetch_step_i" +
      "d\030\003 \003(\003\"N\n\020LabeledStepStats\022\017\n\007step_id\030\001" +
      " \001(\003\022)\n\nstep_stats\030\002 \001(\0132\025.tensorflow.St" +
      "epStats\"=\n\017LoggingResponse\022*\n\004step\030\001 \003(\013" +
      "2\034.tensorflow.LabeledStepStats\"\253\001\n\tTrace" +
      "Opts\022\020\n\010duration\030\001 \001(\001\022\031\n\021use_step_profi" +
      "ler\030\002 \001(\010\022\033\n\023use_kernel_profiler\030\003 \001(\010\022\035" +
      "\n\025use_extended_profiler\030\004 \001(\010\022\030\n\020use_gpu" +
      "_profiler\030\005 \001(\010\022\033\n\023use_sample_profiler\030\006" +
      " \001(\010\"8\n\016TracingRequest\022&\n\007options\030\001 \001(\0132" +
      "\025.tensorflow.TraceOpts\"\021\n\017TracingRespons" +
      "e\"\270\002\n\016RecvBufRequest\022\017\n\007step_id\030\001 \001(\003\022\032\n" +
      "\022buf_rendezvous_key\030\002 \001(\t\022\021\n\tnum_bytes\030\003" +
      " \001(\003\022\017\n\007buf_ptr\030\004 \001(\006\0223\n\017client_locality" +
      "\030\005 \001(\0132\032.tensorflow.DeviceLocality\0223\n\017se" +
      "rver_locality\030\006 \001(\0132\032.tensorflow.DeviceL" +
      "ocality\022/\n\021transport_options\030\007 \001(\0132\024.goo" +
      "gle.protobuf.Any\022\022\n\nsrc_device\030\010 \001(\t\022\022\n\n" +
      "dst_device\030\t \001(\t\022\022\n\nrequest_id\030\n \001(\003\"\222\001\n" +
      "\017RecvBufResponse\022\017\n\007buf_ptr\030\001 \001(\006\022\021\n\tnum" +
      "_bytes\030\002 \001(\003\022\017\n\007is_dead\030\003 \001(\010\022/\n\021transpo" +
      "rt_options\030\004 \001(\0132\024.google.protobuf.Any\022\031" +
      "\n\021send_start_micros\030\005 \001(\003\"g\n\024CompleteGro" +
      "upRequest\022\021\n\tgroup_key\030\001 \001(\005\022\022\n\ngroup_si" +
      "ze\030\002 \001(\005\022\023\n\013device_type\030\003 \001(\t\022\023\n\013device_" +
      "name\030\004 \003(\t\"\216\001\n\025CompleteGroupResponse\022\021\n\t" +
      "group_key\030\001 \001(\005\022\022\n\ngroup_size\030\002 \001(\005\022\023\n\013d" +
      "evice_type\030\003 \001(\t\022\021\n\tnum_tasks\030\004 \001(\005\022\023\n\013d" +
      "evice_name\030\005 \003(\t\022\021\n\ttask_name\030\006 \003(\t\"\227\002\n\027" +
      "CompleteInstanceRequest\022\014\n\004name\030\001 \001(\t\022\014\n" +
      "\004type\030\002 \001(\005\022\'\n\tdata_type\030\003 \001(\0162\024.tensorf" +
      "low.DataType\022+\n\005shape\030\004 \001(\0132\034.tensorflow" +
      ".TensorShapeProto\022\021\n\tgroup_key\030\005 \001(\005\022\022\n\n" +
      "group_size\030\006 \001(\005\022\024\n\014instance_key\030\007 \001(\005\022\023" +
      "\n\013device_type\030\010 \001(\t\022\025\n\rsubdiv_offset\030\t \003" +
      "(\005\022\016\n\006device\030\n \001(\t\022\021\n\tis_source\030\013 \001(\010\"_\n" +
      "\030CompleteInstanceResponse\022\024\n\014instance_ke" +
      "y\030\001 \001(\005\022\023\n\013source_rank\030\002 \001(\005\022\030\n\020communic" +
      "ator_key\030\003 \001(\014\"+\n\026GetStepSequenceRequest" +
      "\022\021\n\tgraph_key\030\001 \003(\003\"7\n\014StepSequence\022\021\n\tg" +
      "raph_key\030\001 \001(\003\022\024\n\014next_step_id\030\002 \001(\003\"J\n\027" +
      "GetStepSequenceResponse\022/\n\rstep_sequence" +
      "\030\001 \003(\0132\030.tensorflow.StepSequenceBm\n\032org." +
      "tensorflow.distruntimeB\014WorkerProtosP\001Z<" +
      "github.com/tensorflow/tensorflow/tensorf" +
      "low/go/core/protobuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.tensorflow.framework.CostGraphProtos.getDescriptor(),
          org.tensorflow.framework.StepStatsProtos.getDescriptor(),
          org.tensorflow.framework.DeviceAttributesProtos.getDescriptor(),
          org.tensorflow.framework.GraphProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
          org.tensorflow.framework.ErrorCodesProtos.getDescriptor(),
          org.tensorflow.framework.ConfigProtos.getDescriptor(),
          org.tensorflow.framework.DebugProtos.getDescriptor(),
          org.tensorflow.framework.NamedTensorProtos.getDescriptor(),
          org.tensorflow.distruntime.ServerProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_GetStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_GetStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusResponse_descriptor,
        new java.lang.String[] { "DeviceAttributes", });
    internal_static_tensorflow_CreateWorkerSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_CreateWorkerSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateWorkerSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "ServerDef", "IsolateSessionState", });
    internal_static_tensorflow_CreateWorkerSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_CreateWorkerSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CreateWorkerSessionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_DeleteWorkerSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeleteWorkerSessionRequest_descriptor,
        new java.lang.String[] { "SessionHandle", });
    internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_DeleteWorkerSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeleteWorkerSessionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RegisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphDef", "HasControlFlow", "GraphOptions", "DebugOptions", "CollectiveGraphKey", });
    internal_static_tensorflow_RegisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphResponse_descriptor,
        new java.lang.String[] { "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_CleanupAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllRequest_descriptor,
        new java.lang.String[] { "Container", });
    internal_static_tensorflow_CleanupAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_ExecutorOpts_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tensorflow_ExecutorOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExecutorOpts_descriptor,
        new java.lang.String[] { "RecordCosts", "RecordTimeline", "RecordPartitionGraphs", "ReportTensorAllocationsUponOom", });
    internal_static_tensorflow_RunGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tensorflow_RunGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "CreateWorkerSessionCalled", "GraphHandle", "StepId", "ExecOpts", "Send", "RecvKey", "IsPartial", "IsLastPartialRun", "StoreErrorsInResponseBody", });
    internal_static_tensorflow_RunGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tensorflow_RunGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphResponse_descriptor,
        new java.lang.String[] { "Recv", "StepStats", "CostGraph", "PartitionGraph", "StatusCode", "StatusErrorMessage", });
    internal_static_tensorflow_CleanupGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphRequest_descriptor,
        new java.lang.String[] { "StepId", });
    internal_static_tensorflow_CleanupGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RecvTensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorRequest_descriptor,
        new java.lang.String[] { "StepId", "RendezvousKey", "DmaOk", "ClientLocality", "ServerLocality", "TransportOptions", "RequestId", });
    internal_static_tensorflow_RecvTensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorResponse_descriptor,
        new java.lang.String[] { "Tensor", "IsDead", "SendStartMicros", "TransportOptions", });
    internal_static_tensorflow_LoggingRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_tensorflow_LoggingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingRequest_descriptor,
        new java.lang.String[] { "EnableRpcLogging", "DisableRpcLogging", "Clear", "FetchStepId", });
    internal_static_tensorflow_LabeledStepStats_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_tensorflow_LabeledStepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LabeledStepStats_descriptor,
        new java.lang.String[] { "StepId", "StepStats", });
    internal_static_tensorflow_LoggingResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_tensorflow_LoggingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingResponse_descriptor,
        new java.lang.String[] { "Step", });
    internal_static_tensorflow_TraceOpts_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_tensorflow_TraceOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TraceOpts_descriptor,
        new java.lang.String[] { "Duration", "UseStepProfiler", "UseKernelProfiler", "UseExtendedProfiler", "UseGpuProfiler", "UseSampleProfiler", });
    internal_static_tensorflow_TracingRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_tensorflow_TracingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_tensorflow_TracingResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_tensorflow_TracingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RecvBufRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_tensorflow_RecvBufRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvBufRequest_descriptor,
        new java.lang.String[] { "StepId", "BufRendezvousKey", "NumBytes", "BufPtr", "ClientLocality", "ServerLocality", "TransportOptions", "SrcDevice", "DstDevice", "RequestId", });
    internal_static_tensorflow_RecvBufResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_tensorflow_RecvBufResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvBufResponse_descriptor,
        new java.lang.String[] { "BufPtr", "NumBytes", "IsDead", "TransportOptions", "SendStartMicros", });
    internal_static_tensorflow_CompleteGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_tensorflow_CompleteGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteGroupRequest_descriptor,
        new java.lang.String[] { "GroupKey", "GroupSize", "DeviceType", "DeviceName", });
    internal_static_tensorflow_CompleteGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_tensorflow_CompleteGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteGroupResponse_descriptor,
        new java.lang.String[] { "GroupKey", "GroupSize", "DeviceType", "NumTasks", "DeviceName", "TaskName", });
    internal_static_tensorflow_CompleteInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_tensorflow_CompleteInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteInstanceRequest_descriptor,
        new java.lang.String[] { "Name", "Type", "DataType", "Shape", "GroupKey", "GroupSize", "InstanceKey", "DeviceType", "SubdivOffset", "Device", "IsSource", });
    internal_static_tensorflow_CompleteInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_tensorflow_CompleteInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CompleteInstanceResponse_descriptor,
        new java.lang.String[] { "InstanceKey", "SourceRank", "CommunicatorKey", });
    internal_static_tensorflow_GetStepSequenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_tensorflow_GetStepSequenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStepSequenceRequest_descriptor,
        new java.lang.String[] { "GraphKey", });
    internal_static_tensorflow_StepSequence_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_tensorflow_StepSequence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_StepSequence_descriptor,
        new java.lang.String[] { "GraphKey", "NextStepId", });
    internal_static_tensorflow_GetStepSequenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_tensorflow_GetStepSequenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStepSequenceResponse_descriptor,
        new java.lang.String[] { "StepSequence", });
    com.google.protobuf.AnyProto.getDescriptor();
    org.tensorflow.framework.CostGraphProtos.getDescriptor();
    org.tensorflow.framework.StepStatsProtos.getDescriptor();
    org.tensorflow.framework.DeviceAttributesProtos.getDescriptor();
    org.tensorflow.framework.GraphProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
    org.tensorflow.framework.ErrorCodesProtos.getDescriptor();
    org.tensorflow.framework.ConfigProtos.getDescriptor();
    org.tensorflow.framework.DebugProtos.getDescriptor();
    org.tensorflow.framework.NamedTensorProtos.getDescriptor();
    org.tensorflow.distruntime.ServerProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
