/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensor_bundle.proto

package org.tensorflow.util;

public interface BundleHeaderProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.BundleHeaderProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of data files in the bundle.
   * </pre>
   *
   * <code>int32 num_shards = 1;</code>
   */
  int getNumShards();

  /**
   * <code>.tensorflow.BundleHeaderProto.Endianness endianness = 2;</code>
   */
  int getEndiannessValue();
  /**
   * <code>.tensorflow.BundleHeaderProto.Endianness endianness = 2;</code>
   */
  org.tensorflow.util.BundleHeaderProto.Endianness getEndianness();

  /**
   * <pre>
   * Versioning of the tensor bundle format.
   * </pre>
   *
   * <code>.tensorflow.VersionDef version = 3;</code>
   */
  boolean hasVersion();
  /**
   * <pre>
   * Versioning of the tensor bundle format.
   * </pre>
   *
   * <code>.tensorflow.VersionDef version = 3;</code>
   */
  org.tensorflow.framework.VersionDef getVersion();
  /**
   * <pre>
   * Versioning of the tensor bundle format.
   * </pre>
   *
   * <code>.tensorflow.VersionDef version = 3;</code>
   */
  org.tensorflow.framework.VersionDefOrBuilder getVersionOrBuilder();
}
