/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: saved_tensor_slice.proto

package org.tensorflow.util;

public interface SavedTensorSlicesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SavedTensorSlices)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This is only present at the first item of each checkpoint file and serves
   * as a table of contents, listing all the tensor slices saved in this file.
   * </pre>
   *
   * <code>.tensorflow.SavedTensorSliceMeta meta = 1;</code>
   */
  boolean hasMeta();
  /**
   * <pre>
   * This is only present at the first item of each checkpoint file and serves
   * as a table of contents, listing all the tensor slices saved in this file.
   * </pre>
   *
   * <code>.tensorflow.SavedTensorSliceMeta meta = 1;</code>
   */
  org.tensorflow.util.SavedTensorSliceMeta getMeta();
  /**
   * <pre>
   * This is only present at the first item of each checkpoint file and serves
   * as a table of contents, listing all the tensor slices saved in this file.
   * </pre>
   *
   * <code>.tensorflow.SavedTensorSliceMeta meta = 1;</code>
   */
  org.tensorflow.util.SavedTensorSliceMetaOrBuilder getMetaOrBuilder();

  /**
   * <pre>
   * This exists in all but the first item of each checkpoint file.
   * </pre>
   *
   * <code>.tensorflow.SavedSlice data = 2;</code>
   */
  boolean hasData();
  /**
   * <pre>
   * This exists in all but the first item of each checkpoint file.
   * </pre>
   *
   * <code>.tensorflow.SavedSlice data = 2;</code>
   */
  org.tensorflow.util.SavedSlice getData();
  /**
   * <pre>
   * This exists in all but the first item of each checkpoint file.
   * </pre>
   *
   * <code>.tensorflow.SavedSlice data = 2;</code>
   */
  org.tensorflow.util.SavedSliceOrBuilder getDataOrBuilder();
}
