/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensor_bundle.proto

package org.tensorflow.util;

public final class TensorBundleProtos {
  private TensorBundleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_BundleHeaderProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_BundleHeaderProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_BundleEntryProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_BundleEntryProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023tensor_bundle.proto\022\ntensorflow\032,tenso" +
      "rflow/core/framework/tensor_shape.proto\032" +
      ",tensorflow/core/framework/tensor_slice." +
      "proto\032%tensorflow/core/framework/types.p" +
      "roto\032(tensorflow/core/framework/versions" +
      ".proto\"\261\001\n\021BundleHeaderProto\022\022\n\nnum_shar" +
      "ds\030\001 \001(\005\022<\n\nendianness\030\002 \001(\0162(.tensorflo" +
      "w.BundleHeaderProto.Endianness\022\'\n\007versio" +
      "n\030\003 \001(\0132\026.tensorflow.VersionDef\"!\n\nEndia" +
      "nness\022\n\n\006LITTLE\020\000\022\007\n\003BIG\020\001\"\322\001\n\020BundleEnt" +
      "ryProto\022#\n\005dtype\030\001 \001(\0162\024.tensorflow.Data" +
      "Type\022+\n\005shape\030\002 \001(\0132\034.tensorflow.TensorS" +
      "hapeProto\022\020\n\010shard_id\030\003 \001(\005\022\016\n\006offset\030\004 " +
      "\001(\003\022\014\n\004size\030\005 \001(\003\022\016\n\006crc32c\030\006 \001(\007\022,\n\006sli" +
      "ces\030\007 \003(\0132\034.tensorflow.TensorSliceProtoB" +
      "l\n\023org.tensorflow.utilB\022TensorBundleProt" +
      "osP\001Z<github.com/tensorflow/tensorflow/t" +
      "ensorflow/go/core/protobuf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TensorSliceProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
          org.tensorflow.framework.VersionsProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_BundleHeaderProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_BundleHeaderProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_BundleHeaderProto_descriptor,
        new java.lang.String[] { "NumShards", "Endianness", "Version", });
    internal_static_tensorflow_BundleEntryProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_BundleEntryProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_BundleEntryProto_descriptor,
        new java.lang.String[] { "Dtype", "Shape", "ShardId", "Offset", "Size", "Crc32C", "Slices", });
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TensorSliceProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
    org.tensorflow.framework.VersionsProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
