/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example_parser_configuration.proto

package org.tensorflow.example;

public final class ExampleParserConfigurationProtos {
  private ExampleParserConfigurationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_VarLenFeatureProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_VarLenFeatureProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FixedLenFeatureProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_FixedLenFeatureProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FeatureConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_FeatureConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExampleParserConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"example_parser_configuration.proto\022\nte" +
      "nsorflow\032,tensorflow/core/framework/tens" +
      "or_shape.proto\032&tensorflow/core/framewor" +
      "k/tensor.proto\032%tensorflow/core/framewor" +
      "k/types.proto\"\243\001\n\022VarLenFeatureProto\022#\n\005" +
      "dtype\030\001 \001(\0162\024.tensorflow.DataType\022!\n\031val" +
      "ues_output_tensor_name\030\002 \001(\t\022\"\n\032indices_" +
      "output_tensor_name\030\003 \001(\t\022!\n\031shapes_outpu" +
      "t_tensor_name\030\004 \001(\t\"\273\001\n\024FixedLenFeatureP" +
      "roto\022#\n\005dtype\030\001 \001(\0162\024.tensorflow.DataTyp" +
      "e\022+\n\005shape\030\002 \001(\0132\034.tensorflow.TensorShap" +
      "eProto\022.\n\rdefault_value\030\003 \001(\0132\027.tensorfl" +
      "ow.TensorProto\022!\n\031values_output_tensor_n" +
      "ame\030\004 \001(\t\"\232\001\n\024FeatureConfiguration\022=\n\021fi" +
      "xed_len_feature\030\001 \001(\0132 .tensorflow.Fixed" +
      "LenFeatureProtoH\000\0229\n\017var_len_feature\030\002 \001" +
      "(\0132\036.tensorflow.VarLenFeatureProtoH\000B\010\n\006" +
      "config\"\276\001\n\032ExampleParserConfiguration\022K\n" +
      "\013feature_map\030\001 \003(\01326.tensorflow.ExampleP" +
      "arserConfiguration.FeatureMapEntry\032S\n\017Fe" +
      "atureMapEntry\022\013\n\003key\030\001 \001(\t\022/\n\005value\030\002 \001(" +
      "\0132 .tensorflow.FeatureConfiguration:\0028\001B" +
      "|\n\026org.tensorflow.exampleB ExampleParser" +
      "ConfigurationProtosP\001Z;github.com/tensor" +
      "flow/tensorflow/tensorflow/go/core/examp" +
      "le\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_VarLenFeatureProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_VarLenFeatureProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_VarLenFeatureProto_descriptor,
        new java.lang.String[] { "Dtype", "ValuesOutputTensorName", "IndicesOutputTensorName", "ShapesOutputTensorName", });
    internal_static_tensorflow_FixedLenFeatureProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_FixedLenFeatureProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_FixedLenFeatureProto_descriptor,
        new java.lang.String[] { "Dtype", "Shape", "DefaultValue", "ValuesOutputTensorName", });
    internal_static_tensorflow_FeatureConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_FeatureConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_FeatureConfiguration_descriptor,
        new java.lang.String[] { "FixedLenFeature", "VarLenFeature", "Config", });
    internal_static_tensorflow_ExampleParserConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_ExampleParserConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExampleParserConfiguration_descriptor,
        new java.lang.String[] { "FeatureMap", });
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor =
      internal_static_tensorflow_ExampleParserConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExampleParserConfiguration_FeatureMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
