/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package org.tensorflow.example;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  boolean hasBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  org.tensorflow.example.BytesList getBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  org.tensorflow.example.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  boolean hasFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  org.tensorflow.example.FloatList getFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  org.tensorflow.example.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  boolean hasInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  org.tensorflow.example.Int64List getInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  org.tensorflow.example.Int64ListOrBuilder getInt64ListOrBuilder();

  org.tensorflow.example.Feature.KindCase getKindCase();
}
