/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package org.tensorflow.example;

public interface FeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Features)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  boolean containsFeature(
      java.lang.String key);
  /**
   * Use {@link #getFeatureMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.tensorflow.example.Feature>
  getFeature();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  java.util.Map<java.lang.String, org.tensorflow.example.Feature>
  getFeatureMap();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */

  org.tensorflow.example.Feature getFeatureOrDefault(
      java.lang.String key,
      org.tensorflow.example.Feature defaultValue);
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */

  org.tensorflow.example.Feature getFeatureOrThrow(
      java.lang.String key);
}
