/*
 * Copyright (c) 2019 by Andrew Charneski.
 *
 * The author licenses this file to you under the
 * Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package org.tensorflow.example;

public interface Int64ListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Int64List)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  java.util.List<java.lang.Long> getValueList();
  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  int getValueCount();
  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  long getValue(int index);
}
